tasks:
  build:
    image: node:carbon
    command:
      - yarn
    args:
      - install
  test:
    image: node:carbon
    command:
      - yarn
    args:
      - test
    when: "heads/master$"
workflow:  
  - build  
  - sail:parallel:
    - test
