language:
  node_js
sudo: false
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
os:
  - linux
  - osx
  - windows
branches:
  only:
    - master
    - devel
install:
  - npm -g install daria
before_script:
  - npm test
script:
  - daria
