language:
  node_js
sudo: false
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
os:
  - linux
  - osx
  - windows
install:
  - yarn global add daria
cache:
  yarn: true
  directories:
    - node_modules
script:
  - daria
