language:
  node_js
sudo: false
node_js:
  - 11
  - 10
  - 9
  - 8
os:
  - linux
  - osx
branches:
  only:
    - devel
    - master
install:
  - npm i
before_script:
  - npm test
script:
  - node index.js
